# Generated by Django 4.2.4 on 2023-08-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='preis',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bestellung',
            name='auftrags_id',
            field=models.CharField(max_length=200, null=200),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
