# Generated by Django 4.2.4 on 2023-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_artikel_preis_alter_bestellung_auftrags_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestellung',
            name='auftrags_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
